title: "The Three Phases of Compose"
subtitle: "Advanced Topics and Compiler Insights"
author: "Daniel Passos"
date: "2025-04-16"
lang: "en"
cover-image: assets/images/cover.png
toc: true
toc-depth: 2
fontsize: 11pt
geometry: margin=1in
documentclass: book
preview: false
