name: Build Preview

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Pandoc + LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pandoc \
            texlive-xetex texlive-fonts-recommended texlive-latex-extra \
            fonts-firacode

      - name: Make build.sh executable
        run: chmod +x build.sh

      - name: Build Preview
        run: |
          mkdir -p output
          bash build.sh --preview

      - name: Upload Preview
        uses: actions/upload-artifact@v4
        with:
          name: compose-book
          path: |
            output/the-three-phases-of-compose-preview.pdf
            output/the-three-phases-of-compose-preview.epub
