name: Build Preview

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Pandoc + LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pandoc \
            texlive-xetex texlive-fonts-recommended texlive-latex-extra \
            fonts-firacode


      - name: Generate chapters.txt
        run: bash chapters.sh

      - name: Build Chapter Preview
        run: |
          mkdir -p output
          bash build.sh --preview

      - name: Upload Chapter Preview PDF
        uses: actions/upload-artifact@v4
        with:
          name: compose-chapter-preview
          path: output/preview.pdf

      - name: Build Full Book
        run: bash build.sh

      - name: Upload Book Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compose-book
          path: |
            output/the-three-phases-of-compose-preview.pdf
            output/the-three-phases-of-compose-preview.epub
