name: Build Book

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Pandoc + LaTeX
        uses: docker://pandoc/latex:latest

      - name: Generate chapters.txt
        run: bash chapters.sh

      - name: Build Chapter Preview
        run: |
          mkdir -p output
          bash build-preview.sh 01-phase-1-composition/01-what-exactly-triggers-recomposition.md

      - name: Upload Chapter Preview PDF
        uses: actions/upload-artifact@v4
        with:
          name: compose-chapter-preview
          path: book/output/preview.pdf

      - name: Build Full Book
        run: bash build.sh

      - name: Upload Book Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compose-book
          path: |
            book/output/the-three-phases-of-compose.pdf
            book/output/the-three-phases-of-compose.epub
